name: Build & Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages:    write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) ➜ Ajoute les librairies système indispensables à AVIF
      - name: Install system libs for AVIF
        run: |
          sudo apt-get update
          sudo apt-get install -y libheif-dev libde265-dev

      # 3) Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 4) Dépendances npm
      - name: Install dependencies
        run: npm ci

      # 5) Build CSS / JS
      - name: Build assets
        run: |
          npm run build:css
          npm run build:js

      # 6) Hugo Extended
      - name: Install Hugo Extended
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # 7) Générer le site
      - name: Build site
        run: hugo --gc --minify

      # 8) Validation HTML (optionnel)
      - name: Validate HTML
        run: |
          npm install -g html-validate
          html-validate "public/**/*.html"
        continue-on-error: true

      # 9) Déploiement sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: public
          github_token: ${{ secrets.GITHUB_TOKEN }}
